apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-cup
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea-cup
  template:
    metadata:
      labels:
        app: tea-cup
    spec:
      containers:
        - name: tea-cup
          image: ghcr.io/labotomy-dot-dev/coffee-cup-tea-cup:prod-35
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "prod"
